"""empty message

Revision ID: 64db2d155d41
Revises: 
Create Date: 2020-12-26 15:29:26.121242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64db2d155d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录日期'),
    sa.Column('last_ip', sa.String(length=16), nullable=True, comment='最后登录日期'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('body', sa.Text(), nullable=False, comment='内容'),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='关联对象'),
    sa.ForeignKeyConstraint(['author_id'], ['tb_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_comments')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
